// Generated by CoffeeScript 1.6.3
var _this = this;

window.addEventListener("load", function(e) {
  var Setup, audioctx, gain, osc, play;
  window.removeEventListener("load", arguments.callee, false);
  if (typeof webkitAudioContext !== "undefined") {
    audioctx = new webkitAudioContext();
  } else if (typeof AudioContext !== "undefined") {
    audioctx = new AudioContext();
  }
  play = 0;
  osc = audioctx.createOscillator();
  gain = audioctx.createGainNode();
  osc.connect(gain);
  gain.connect(audioctx.destination);
  Setup = function() {
    if (play === 0) {
      osc.noteOn(0);
      play = 1;
    }
    osc.type = 2;
    gain.gain.value = 1;
    return window.addEventListener('devicemotion', function(event) {
      var gv, x, y, z;
      gv = event.accelerationIncludingGravity;
      x = Math.abs(gv.x);
      y = Math.abs(gv.y);
      z = Math.abs(gv.z);
      return osc.frequency.value = 440 / 9.8 * (x + y + z);
    });
  };
  if (window.navigator.standalone) {
    return Setup();
  } else {
    return document.getElementById("info").addEventListener("touchstart", Setup);
  }
});
